---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iaas.agrrh.com
  resources:
  - nodeagreements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iaas.agrrh.com
  resources:
  - nodeagreements/finalizers
  verbs:
  - update
- apiGroups:
  - iaas.agrrh.com
  resources:
  - nodeagreements/status
  verbs:
  - get
  - patch
  - update
